require 'lib/markup_validator/markup_validator'
require 'lib/markup_validator/exceptions'
require 'lib/markup_validator/constants'
require 'lib/markup_validator/results'
require 'lib/markup_validator/message'
